{
 "title": "CryptoTracking",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate of volume change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(coin_volume_usd{instance=\"192.168.1.66:9029\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of price change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "rate(coin_price_usd{instance=\"192.168.1.66:9029\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Breakout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current Price",
   "type": "timeseries",
   "description": "The current spot purchase price",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "coin_price_usd{instance=\"192.168.1.66:9029\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bid Price",
   "type": "timeseries",
   "description": "The bid price of the coin",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "coin_bid_usd{instance=\"192.168.1.66:9029\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ask Price",
   "type": "timeseries",
   "description": "The ask price of the coin.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "coin_ask_usd{instance=\"192.168.1.66:9029\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coin Volume",
   "type": "timeseries",
   "description": "The trading volume of the coin.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "coin_volume_usd{instance=\"192.168.1.66:9029\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}