{
 "title": "CryptoTracking",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "cryptocoin", "query": { "query": "label_values(coin)" } }
  ]
 },
 "panels": [
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "coin_price_usd{instance=\"$instance\", coin=\"$cryptocoin\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "coin_volume_usd{instance=\"$instance\", coin=\"$cryptocoin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spread",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "coin_ask_usd{instance=\"$instance\", coin=\"$cryptocoin\"} - coin_bid_usd{instance=\"$instance\", coin=\"$cryptocoin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Breakout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Current Price",
   "type": "timeseries",
   "description": "The current spot purchase price",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "coin_price_usd{instance=\"$instance\",coin=\"$cryptocoin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bid Price",
   "type": "timeseries",
   "description": "The bid price of the coin",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "coin_bid_usd{instance=\"$instance\", coin=\"$cryptocoin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ask Price",
   "type": "timeseries",
   "description": "The ask price of the coin.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "coin_ask_usd{instance=\"$instance\", coin=\"$cryptocoin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coin Volume",
   "type": "timeseries",
   "description": "The trading volume of the coin.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "coin_volume_usd{instance=\"$instance\", coin=\"$cryptocoin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of volume change",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "rate(coin_volume_usd{instance=\"$instance\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of price change",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "rate(coin_price_usd{instance=\"$instance\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}